services:
    _defaults:
        autowire: true

    Crassula\Bundle\GoogleCloudErrorReportingBundle\Service\ErrorNotifier:
        '@Crassula\Bundle\GoogleCloudErrorReportingBundle\Service\ErrorReporter'

    Crassula\Bundle\GoogleCloudErrorReportingBundle\Service\ErrorReporter:
        public: true
        arguments:
            $config: '%crassula_google_cloud_error_reporting.config%'

    Crassula\Bundle\GoogleCloudErrorReportingBundle\EventListener\ReportErrorListener: ~

    Psr\Log\LoggerInterface: '@monolog.logger'
